services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - workout-tracker-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "psql -U workout -d workout_tracker -c 'select 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  workout-tracker-db:
